language: node_js
sudo: false
node_js:
  - "node"
  - "10"
  - "12"
before_install:
  - sudo apt-get -qq update
  - sudo add-apt-repository -y ppa:inkscape.dev/stable && sudo apt-get update && sudo apt-get install -y inkscape
  - inkscape --version
  - inkscape --help
  # - sudo apt-get install -y inkscape
install:
  - npm install --dev
script:
  - inkscape --version
  - npm test
after_success:
  - npm run coveralls