language: node_js
sudo: false
node_js:
  - "node"
  - "6"
  - "8"
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y inkscape
install:
  - npm install --dev
script:
  - npm test
after_success:
  - npm run coveralls